version: '3'
services:
  db:
    image: mysql:5.7.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
